# Generated by Django 4.2.6 on 2024-08-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_fichainscripcion_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainscripcion',
            name='direccion',
            field=models.TextField(max_length=200),
        ),
    ]
