# Generated by Django 4.2.6 on 2024-08-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_fichainscripcion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainscripcion',
            name='direccion_laboral',
            field=models.TextField(max_length=200),
        ),
    ]
