# Generated by Django 4.2.6 on 2024-08-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_alter_fichainscripcion_direccion_laboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainscripcion',
            name='direccion_laboral',
            field=models.TextField(max_length=100),
        ),
    ]
