# Generated by Django 4.2.6 on 2024-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_remove_categoria_uc_remove_marca_uc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='default_name', help_text='Nombre de la categoria', max_length=25, unique=True),
        ),
    ]
