# Generated by Django 4.2.6 on 2024-08-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Nombre', help_text='Nombre de la categoria', max_length=25, unique=True),
        ),
    ]
