# Generated by Django 4.2.6 on 2024-08-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a'), ('O', 'Otro')], max_length=1)),
                ('grado_instruccion', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundaria'), ('T', 'Técnico'), ('U', 'Universitario')], max_length=1)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('centro_laboral', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo_laboral', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_laboral', models.CharField(max_length=200)),
                ('distrito_laboral', models.CharField(max_length=100)),
                ('provincia_laboral', models.CharField(max_length=100)),
                ('departamento_laboral', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
