# Generated by Django 4.2.6 on 2024-08-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_fichainscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='inv.fichainscripcion'),
        ),
    ]
