# Generated by Django 4.2.6 on 2024-08-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_idioma_frase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
