# Generated by Django 4.2.6 on 2024-08-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
